Document: testreduce
Title: Debian testreduce Manual
Author: <insert document author here>
Abstract: This manual describes what testreduce is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/testreduce/testreduce.sgml.gz

Format: postscript
Files: /usr/share/doc/testreduce/testreduce.ps.gz

Format: text
Files: /usr/share/doc/testreduce/testreduce.text.gz

Format: HTML
Index: /usr/share/doc/testreduce/html/index.html
Files: /usr/share/doc/testreduce/html/*.html
